data:
    name: 'robotcar'
    sequences: ['overcast-reference', 'sun', 'dusk', 'night', 'night-rain']
    resize_max: 960
model:
    name: 'hf_net_shared'
    image_channels: 1
    local:
        detector_threshold: 0.005
