data:
    name: 'colmap'
    sequences: [
        'british_museum', 'florence_cathedral_side',
        'lincoln_memorial_statue', 'london_bridge',
        'milan_cathedral', 'mount_rushmore',
        'piazza_san_marco', 'reichstag', 'sagrada_familia',
        'st_pauls_cathedral', 'united_states_capitol']
model:
    name: 'netvlad_original'
    local_descriptor_layer: 'conv3_3'
    image_channels: 1
weights: 'vd16_pitts30k_conv5_3_vlad_preL2_intra_white/vd16_pitts30k_conv5_3_vlad_preL2_intra_white'
