data:
    name: 'cmu'
    sequences: ['slice2', 'slice3', 'slice4', 'slice5', 'slice6', 'slice7',
                'slice8', 'slice9', 'slice10', 'slice17']
    load_db: true
    load_queries: true
    resize_max: 1024
model:
    name: 'super_point'
    nms_radius: 0
    detector_threshold: 0.005
    image_channels: 1
