data:
    name: 'robotcar'
    sequences: ['overcast-reference', 'sun', 'dusk', 'night', 'night-rain']
    resize_max: 960
model:
    name: 'super_point'
    nms_radius: 0
    detector_threshold: 0.005
    image_channels: 1
